"""ATSC 1.0 carrier-detection algorithms (offline / replay).

Each detector takes a complex-IQ buffer captured at the channel center
plus the sample rate, and returns a `score` (higher = stronger match)
along with any algorithm-specific intermediate values useful for tuning.

Detectors implemented here:

  pilot_snr       — current method: peak in pilot bin vs out-of-band
                    noise. Cheap. Triggers on any narrow tone.
  pilot_sharpness — peak / ±100 kHz neighborhood mean. Distinguishes a
                    CW pilot from a broadband peak.
  vsb_asymmetry   — power above pilot vs below pilot (3 MHz each).
                    ATSC's signature shape; ~0 dB on noise / OFDM.
  pn511_corr      — cross-correlate the captured baseband against the
                    known 511-symbol pseudo-noise pattern. Strong score
                    is the gold standard "this is real ATSC" — same
                    fingerprint hardware demod chips use.
  spectral_mask   — correlation of the captured PSD with the published
                    ATSC spectral envelope.
  field_autocorr  — autocorrelation at the 24.18 ms field period. ATSC
                    repeats its field-sync structure every 313 segments;
                    this pulls a peak out of the data even when no
                    individual feature is strong.

The `combine` helpers express how to turn raw scores into a binary
decision; the harness (harness.py) sweeps thresholds and scores against
ground_truth_dc.json.
"""

from __future__ import annotations

from typing import Sequence
import numpy as np

# ATSC 8-VSB pilot offset from channel center.
PILOT_OFFSET_HZ = -2.690e6
# ATSC field period (313 segments × 832 symbols / 10.762 Msym/s).
FIELD_PERIOD_SEC = 24.18e-3
# Symbol rate.
SYMBOL_RATE = 10.762237e6
# PN511 sequence — the 511-bit pseudo-noise pattern that begins every
# field-sync segment. Hard-coded here so this module is self-contained
# (it lives in atsc_pnXXX_impl.h on the C++ side). Generated by the
# upstream gr-dtv code as `init_field_sync_511`.
PN511 = np.array([
    0,0,0,0,1,0,1,0,0,0,1,0,1,1,1,1,0,0,1,0,1,0,1,1,1,0,1,1,0,1,0,1,
    1,0,1,0,1,1,1,1,1,1,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,1,0,0,
    0,1,0,1,0,0,1,1,1,1,1,1,0,1,1,1,1,0,0,1,1,0,0,1,0,1,1,1,0,0,0,0,
    0,1,1,1,0,1,1,1,1,1,0,1,1,0,0,0,0,0,1,1,0,0,0,1,1,1,1,0,1,0,0,1,
    0,1,1,1,1,1,1,0,0,0,0,1,1,1,0,0,1,1,1,1,1,1,1,0,0,0,0,1,0,1,1,1,
    0,0,0,1,1,1,1,1,0,1,0,0,0,1,1,0,1,0,1,1,0,0,1,1,1,1,1,0,1,0,0,0,
    1,0,0,0,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,1,0,0,0,0,1,1,1,1,0,0,0,1,
    1,1,0,1,0,0,1,0,1,0,0,0,1,1,1,1,1,1,0,1,1,1,0,0,1,1,1,1,1,0,0,1,
    1,1,1,0,1,1,1,1,0,0,1,1,0,1,1,0,1,1,1,1,1,0,1,0,1,1,0,1,0,0,1,0,
    1,0,1,1,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,1,0,1,0,1,1,1,0,0,1,0,0,1,
    1,1,0,1,0,1,0,0,0,1,0,0,1,1,1,1,0,1,1,0,1,1,1,1,1,0,0,1,0,1,1,1,
    1,1,0,1,0,0,1,1,1,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,1,1,1,1,1,1,1,1,
    1,1,1,0,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,0,1,1,1,0,0,1,0,1,1,0,0,1,
    1,1,1,1,1,1,1,1,1,1,0,0,1,0,0,1,0,0,1,0,1,0,1,1,0,0,1,0,0,1,1,1,
    1,1,1,1,1,0,0,1,1,1,0,0,0,1,0,1,1,1,1,1,1,1,1,1,0,0,0,1,1,0,1,0,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
], dtype=np.int8)


def _fft_psd(samples: np.ndarray, n_fft: int = 16384):
    """Window + FFT-shift, return magnitude-squared spectrum."""
    n = min(samples.size, n_fft)
    if n < 1024:
        return None, None
    win = np.hanning(n).astype(np.float32)
    spec = np.fft.fftshift(np.fft.fft(samples[:n] * win, n_fft))
    return np.abs(spec) ** 2, n_fft


# ── 1. Pilot SNR (the existing crude method) ─────────────────────
def pilot_snr(samples: np.ndarray, sample_rate: int) -> dict:
    psd, n_fft = _fft_psd(samples)
    if psd is None:
        return {"score": float("-inf")}
    bin_hz = sample_rate / n_fft
    pilot_bin = n_fft // 2 + int(round(PILOT_OFFSET_HZ / bin_hz))
    win_bins = max(1, int(round(2e3 / bin_hz)))
    lo = max(0, pilot_bin - win_bins)
    hi = min(n_fft, pilot_bin + win_bins + 1)
    pilot_peak = float(np.max(psd[lo:hi])) if hi > lo else 0.0
    margin_bins = int(round(3.5e6 / bin_hz))
    oob_lo = psd[:max(0, n_fft // 2 - margin_bins)]
    oob_hi = psd[min(n_fft, n_fft // 2 + margin_bins):]
    noise_ref = np.concatenate([oob_lo, oob_hi]) if (oob_lo.size + oob_hi.size) else psd
    noise = float(np.median(noise_ref)) if noise_ref.size else 1e-20
    snr_db = 10.0 * np.log10(pilot_peak / max(noise, 1e-20) + 1e-20)
    return {"score": snr_db}


# ── 2. Pilot sharpness ───────────────────────────────────────────
def pilot_sharpness(samples: np.ndarray, sample_rate: int) -> dict:
    psd, n_fft = _fft_psd(samples)
    if psd is None:
        return {"score": float("-inf")}
    bin_hz = sample_rate / n_fft
    pilot_bin = n_fft // 2 + int(round(PILOT_OFFSET_HZ / bin_hz))
    pilot_win = max(1, int(round(2e3 / bin_hz)))
    plo = max(0, pilot_bin - pilot_win)
    phi = min(n_fft, pilot_bin + pilot_win + 1)
    pilot_peak = float(np.max(psd[plo:phi])) if phi > plo else 0.0
    nbhd_win = int(round(100e3 / bin_hz))
    nlo = max(0, pilot_bin - nbhd_win)
    nhi = min(n_fft, pilot_bin + nbhd_win + 1)
    nbhd = psd[nlo:nhi].copy()
    inner_lo = max(0, plo - nlo)
    inner_hi = max(inner_lo, phi - nlo)
    nbhd[inner_lo:inner_hi] = 0
    nz = nbhd[nbhd > 0]
    nbhd_mean = float(np.mean(nz)) if nz.size else 1e-20
    score_db = 10.0 * np.log10(pilot_peak / max(nbhd_mean, 1e-20) + 1e-20)
    return {"score": score_db}


# ── 3. VSB asymmetry ─────────────────────────────────────────────
def vsb_asymmetry(samples: np.ndarray, sample_rate: int) -> dict:
    psd, n_fft = _fft_psd(samples)
    if psd is None:
        return {"score": float("-inf")}
    bin_hz = sample_rate / n_fft
    pilot_bin = n_fft // 2 + int(round(PILOT_OFFSET_HZ / bin_hz))
    bins_3m = max(1, int(round(3.0e6 / bin_hz)))
    above = psd[pilot_bin:min(n_fft, pilot_bin + bins_3m)]
    below = psd[max(0, pilot_bin - bins_3m):pilot_bin]
    above_pow = float(np.mean(above)) if above.size else 0.0
    below_pow = float(np.mean(below)) if below.size else 1e-20
    score_db = 10.0 * np.log10(above_pow / max(below_pow, 1e-20) + 1e-20)
    return {"score": score_db}


# ── 4. PN511 cross-correlation ───────────────────────────────────
def _pn511_baseband_reference(sample_rate: int) -> np.ndarray:
    """Build a complex-baseband 8-VSB-shaped reference for the 511-symbol
    PN sequence at the given SDR sample rate. Symbols are mapped to ±5
    (matching gr-dtv's bin_map convention) and pulse-shaped by a simple
    raised-cosine. The pilot offset is applied so the resulting waveform
    sits at PILOT_OFFSET_HZ relative to baseband DC — same as the live
    capture's pilot location."""
    # Map PN511 bits 0/1 to ±1 symbol values.
    sym = np.where(PN511 == 1, +1.0, -1.0).astype(np.float32)
    # Upsample to the SDR sample rate. ATSC symbol rate is 10.762 MHz;
    # capture rate is typically 8 MHz, i.e. 0.7437 samples per symbol.
    sps = sample_rate / SYMBOL_RATE
    n_out = int(np.ceil(sym.size * sps))
    # Sample-rate convert via nearest-neighbor + raised-cosine smoothing.
    idx = np.minimum(sym.size - 1, np.arange(n_out) / sps).astype(int)
    upsampled = sym[idx]
    # Smooth with a short raised-cosine-ish kernel (~3 sample window).
    kernel = np.array([0.25, 0.5, 0.25], dtype=np.float32)
    shaped = np.convolve(upsampled, kernel, mode="same").astype(np.complex64)
    # Frequency-shift to put the reference at PILOT_OFFSET_HZ.
    t = np.arange(shaped.size) / sample_rate
    shaped *= np.exp(2j * np.pi * PILOT_OFFSET_HZ * t).astype(np.complex64)
    # Conjugate-time-reverse for use as an FIR matched filter.
    return shaped[::-1].conj()


_pn511_ref_cache: dict[int, np.ndarray] = {}


def pn511_corr(samples: np.ndarray, sample_rate: int) -> dict:
    """Match-filter the input against the PN511 baseband reference.
    Returns peak score (dB above mean magnitude) and, for diagnostics,
    the location of the peak within the capture."""
    if sample_rate not in _pn511_ref_cache:
        _pn511_ref_cache[sample_rate] = _pn511_baseband_reference(sample_rate)
    ref = _pn511_ref_cache[sample_rate]
    if samples.size < ref.size + 1024:
        return {"score": float("-inf"), "peak_idx": -1}
    # FFT-based convolution for speed. Result length = N + M - 1.
    n_out = samples.size + ref.size - 1
    n_fft = 1 << int(np.ceil(np.log2(n_out)))
    A = np.fft.fft(samples, n_fft)
    B = np.fft.fft(ref, n_fft)
    corr = np.fft.ifft(A * B)[:n_out]
    mag = np.abs(corr).astype(np.float32)
    peak = float(np.max(mag))
    # Reference noise floor: median of mag away from the peak.
    peak_idx = int(np.argmax(mag))
    mask = np.ones_like(mag, dtype=bool)
    guard = ref.size  # exclude one ref-length on each side of the peak
    mask[max(0, peak_idx - guard):min(mag.size, peak_idx + guard)] = False
    noise_ref = mag[mask]
    noise = float(np.median(noise_ref)) if noise_ref.size else 1e-20
    score_db = 20.0 * np.log10(peak / max(noise, 1e-20) + 1e-20)
    # ATSC has one PN511 per field (24.18 ms). For longer captures, find
    # secondary peaks and compute their period; report period match.
    field_samples = int(round(FIELD_PERIOD_SEC * sample_rate))
    period_score = 0.0
    if mag.size >= 2 * field_samples:
        # Look for a second peak roughly field_samples away from the first.
        lookahead_lo = peak_idx + int(0.9 * field_samples)
        lookahead_hi = min(mag.size, peak_idx + int(1.1 * field_samples))
        if lookahead_hi > lookahead_lo:
            second = float(np.max(mag[lookahead_lo:lookahead_hi]))
            period_score = 20.0 * np.log10(second / max(noise, 1e-20) + 1e-20)
    return {
        "score": score_db,
        "period_score": period_score,
        "peak_idx": peak_idx,
    }


# ── 5. Spectral mask compliance ──────────────────────────────────
def spectral_mask(samples: np.ndarray, sample_rate: int) -> dict:
    """Correlate the in-band PSD against the expected ATSC envelope:
    a flat top from pilot to pilot+5.38 MHz with sharp roll-off below
    pilot. Returns a similarity score in [-1, +1]."""
    psd, n_fft = _fft_psd(samples)
    if psd is None:
        return {"score": float("-inf")}
    bin_hz = sample_rate / n_fft
    pilot_bin = n_fft // 2 + int(round(PILOT_OFFSET_HZ / bin_hz))
    bins_3m = max(1, int(round(3.0e6 / bin_hz)))
    region = slice(max(0, pilot_bin - bins_3m // 2),
                    min(n_fft, pilot_bin + 2 * bins_3m))
    actual = psd[region]
    if actual.size < 32:
        return {"score": float("-inf")}
    # Build the expected mask in the same region.
    rel_bins = np.arange(actual.size) - (pilot_bin - region.start)
    rel_hz = rel_bins * bin_hz
    expected = np.zeros_like(actual, dtype=np.float32)
    # Flat top from pilot to pilot+5.38 MHz; fast roll-off below pilot.
    expected[(rel_hz >= 0) & (rel_hz <= 5.38e6)] = 1.0
    # Vestigial portion: linear ramp 0 → 0.5 from -0.31 MHz to pilot.
    vsb_mask = (rel_hz < 0) & (rel_hz > -0.31e6)
    expected[vsb_mask] = 0.5 * (rel_hz[vsb_mask] + 0.31e6) / 0.31e6
    # Pearson correlation between actual (log) and expected.
    actual_db = 10.0 * np.log10(actual + 1e-20)
    actual_db -= np.mean(actual_db)
    expected_z = expected - np.mean(expected)
    denom = (np.std(actual_db) * np.std(expected_z))
    if denom <= 0:
        return {"score": float("-inf")}
    corr = float(np.mean(actual_db * expected_z) / denom)
    return {"score": corr}


# ── 6. Field-period autocorrelation ──────────────────────────────
def field_autocorr(samples: np.ndarray, sample_rate: int) -> dict:
    """Compute correlation at exactly the ATSC field period (24.18 ms).
    Real ATSC: nonzero coherence due to repeating FS/segment-sync
    structure. Random noise: ≈0."""
    lag = int(round(FIELD_PERIOD_SEC * sample_rate))
    if samples.size < 2 * lag + 1024:
        return {"score": float("-inf")}
    a = samples[:samples.size - lag]
    b = samples[lag:]
    # Normalized correlation magnitude.
    corr = np.mean(a * np.conj(b))
    energy_a = np.mean(np.abs(a) ** 2)
    energy_b = np.mean(np.abs(b) ** 2)
    denom = np.sqrt(energy_a * energy_b)
    if denom <= 0:
        return {"score": float("-inf")}
    coherence = float(np.abs(corr) / denom)
    score_db = 20.0 * np.log10(coherence + 1e-20)
    return {"score": score_db, "coherence": coherence}


DETECTORS = {
    "pilot_snr": pilot_snr,
    "pilot_sharpness": pilot_sharpness,
    "vsb_asymmetry": vsb_asymmetry,
    "pn511_corr": pn511_corr,
    "spectral_mask": spectral_mask,
    "field_autocorr": field_autocorr,
}


def run_all(samples: np.ndarray, sample_rate: int) -> dict:
    """Convenience: run every detector, return {name: result_dict}."""
    return {name: fn(samples, sample_rate) for name, fn in DETECTORS.items()}
